Add federated credentials instructions
Azure/Azure-Verified-Modules pull request #1207
Opened 2024-07-18 10:42 UTC by NanaXiong00

# Overview/Summary

Add federated credentials instructions.

## This PR fixes/adds/changes/removes

Add secret setup instructions for SP using federated credentials.

### Breaking Changes

none

## As part of this Pull Request I have

- [x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Verified-Modules/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Verified-Modules/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Verified-Modules/)
- [ ] Ensured PR tests are passing
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

@vhvb1989 for notification.

2024-07-18 12:01 UTC, AlexanderSehr requested changes
Presumably, this PR is dependent on https://github.com/Azure/bicep-registry-modules/pull/2701

Just creating this comment to make sure the PR is not accidently merged :)

cc: @eriqua

2024-07-19 08:44 UTC, v-xuto commented
@vhvb1989 Please help review this PR.

2024-07-19 18:14 UTC, vhvb1989 commented
> Presumably, this PR is dependent on [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701)
> 
> Just creating this comment to make sure the PR is not accidently merged :)
> 
> cc: @eriqua

@AlexanderSehr , [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701) seems weird. It looks like it is creating a list of modules which takes too long for OIDC.  I assume that's because the token gets expired and `azure/login@v2` doesn't auto-refresh?

2024-07-19 18:48 UTC, AlexanderSehr commented
> > Presumably, this PR is dependent on [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701)
> > Just creating this comment to make sure the PR is not accidently merged :)
> > cc: @eriqua
> 
> @AlexanderSehr , [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701) seems weird. It looks like it is creating a list of modules which takes too long for OIDC. I assume that's because the token gets expired and `azure/login@v2` doesn't auto-refresh?

'Weird' is a strong word 😄 It's a draft PR and @eriqua is working hard to get OIDC working in it 😉 

And yes, it seems that if you use a Service Principal for federated credentials, you run into a timeout after 1h. However, this may not be the same if using a managed identity which is being tested in a different branch.

I don't have the details as I've not been working on the code myself, so let's give @eriqua some time to figure the best option out 💪

2024-07-22 21:55 UTC, vhvb1989 commented
> > > Presumably, this PR is dependent on [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701)
> > > Just creating this comment to make sure the PR is not accidently merged :)
> > > cc: @eriqua
> > 
> > 
> > @AlexanderSehr , [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701) seems weird. It looks like it is creating a list of modules which takes too long for OIDC. I assume that's because the token gets expired and `azure/login@v2` doesn't auto-refresh?
> 
> 'Weird' is a strong word 😄 It's a draft PR and @eriqua is working hard to get OIDC working in it 😉
> 
> And yes, it seems that if you use a Service Principal for federated credentials, you run into a timeout after 1h. However, this may not be the same if using a managed identity which is being tested in a different branch.
> 
> I don't have the details as I've not been working on the code myself, so let's give @eriqua some time to figure the best option out 💪

You are totally right. I shouldn't have said `weird`. My apologies.

I've added some comments to that PR.  I think you pointed out the same thing that I was curious about.  The use of OIDC and client-secret for the same gh-action called my attention as an interesting approach. I wonder if there could be a way to use only OIDC for all.

2024-07-23 06:52 UTC, AlexanderSehr commented
> > > > Presumably, this PR is dependent on [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701)
> > > > Just creating this comment to make sure the PR is not accidently merged :)
> > > > cc: @eriqua
> > > 
> > > 
> > > @AlexanderSehr , [Azure/bicep-registry-modules#2701](https://github.com/Azure/bicep-registry-modules/pull/2701) seems weird. It looks like it is creating a list of modules which takes too long for OIDC. I assume that's because the token gets expired and `azure/login@v2` doesn't auto-refresh?
> > 
> > 
> > 'Weird' is a strong word 😄 It's a draft PR and @eriqua is working hard to get OIDC working in it 😉
> > And yes, it seems that if you use a Service Principal for federated credentials, you run into a timeout after 1h. However, this may not be the same if using a managed identity which is being tested in a different branch.
> > I don't have the details as I've not been working on the code myself, so let's give @eriqua some time to figure the best option out 💪
> 
> You are totally right. I shouldn't have said `weird`. My apologies.
> 
> I've added some comments to that PR. I think you pointed out the same thing that I was curious about. The use of OIDC and client-secret for the same gh-action called my attention as an interesting approach. I wonder if there could be a way to use only OIDC for all.

Hey @vhvb1989,
there absolutely is. As said, @eriqua was working on the topic in the background and opened this draft PR after working her way through some misleading docs and performing some much needed tests: https://github.com/Azure/bicep-registry-modules/pull/2757

Aside from some AZ CLI issue that causes the logic to fail refreshing the token, it seems to work very well with a managed identity. 

We had a longer chat about the matter yesterday, and it's likely that we'll merge the change in as soon as @eriqua is back (she's currenlty out of office) and enable both the current credential-based as well as the new OIDC approach for authentication (to avoid breaking changes etc.) and after a grace period cut over completely 💪

2024-08-31 14:51 UTC, eriqua commented
Moving to draft as this would require alignment with the actual implementation (still under testing). Ref https://github.com/Azure/bicep-registry-modules/pull/2792 for latest development

2025-01-18 14:46 UTC, eriqua commented
Thanks @NanaXiong00 and @vhvb1989 for raising this PR and supporting the topic.  Closing as covered by #1773

2025-01-18 14:46 UTC, closed without merging