triage updates; BRM triage
Azure/Azure-Verified-Modules pull request #215
Opened 2023-10-21 04:41 UTC by matebarabas

# Overview/Summary

Triage updates and adding guidance for BRM triage

## This PR fixes/adds/changes/removes

see above

### Breaking Changes

n/a

## As part of this Pull Request I have

- [x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Verified-Modules/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Verified-Modules/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Verified-Modules/)
- [ ] Ensured PR tests are passing
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2023-10-24 10:47 UTC, jtracey93 requested changes
Can we also fix the index page for help and support not working 
![image](https://github.com/Azure/Azure-Verified-Modules/assets/41163455/3dd0f549-982b-4e8d-98bd-65233d5fae34)

2023-10-24 10:47 UTC, jtracey93 commented on utilities/repo-automation/brm/github/workflows/csv-label-sync.yml
Why this, the file paths wont work as not BRM specific

2023-10-24 10:47 UTC, jtracey93 commented on utilities/repo-automation/tf/github/policies/scheduledSearches.yml
This should be PR'd into the TF repo template. As well as a label sync one and the label sync script

2023-10-24 18:20 UTC, matebarabas commented
Good catch on the navigation/menu items. I just fixed everything.

2023-10-24 18:23 UTC, matebarabas commented on utilities/repo-automation/brm/github/workflows/csv-label-sync.yml
Correct, nothing was changed in this file (yet). The intent was to just move it here as a placeholder- to have an independent copy - for the time being. Then update it for BRM's requirements with you and decide if we want to keep a master copy here, or just the have the version living in BRM.

2023-10-24 18:24 UTC, matebarabas commented on utilities/repo-automation/tf/github/policies/scheduledSearches.yml
Similar idea as mentioned above. The intent is to have a master copy before we place a copy into the repo template (this file was however updated to reflect Terraform's requirements).

2023-10-25 09:26 UTC, jtracey93 requested changes
lets remove the files that dont need to be in here and then we can merge it

2023-10-25 09:26 UTC, jtracey93 commented on utilities/repo-automation/brm/github/workflows/csv-label-sync.yml
i vote to just have it BRM, we dont need 2 sources of truth 👍

2023-10-25 09:26 UTC, jtracey93 commented on utilities/repo-automation/tf/github/policies/scheduledSearches.yml
same as other comment, only have it in the template repo

2023-10-25 19:48 UTC, jtracey93 approved these changes
LGTM

2023-10-25 19:49 UTC, merged