Add spec for module version
Azure/Azure-Verified-Modules pull request #314
Opened 2023-11-20 06:50 UTC by lonegunmanb

# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes adds specs for Terraform module's `version`.

### Breaking Changes

## As part of this Pull Request I have

- [ ] Read the Contribution Guide and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Verified-Modules/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Verified-Modules/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Verified-Modules/)
- [ ] Ensured PR tests are passing
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2023-11-20 10:51 UTC, jtracey93 requested changes
Looks good just a bit of tidying up

2023-11-20 10:51 UTC, jtracey93 commented on docs/content/specs/terraform/_index.md
> +
```suggestion
```

2023-11-20 10:51 UTC, jtracey93 approved these changes
LGTM

2023-11-24 06:48 UTC, lonegunmanb commented
I'm closing is pr in favour of #332

2023-11-24 06:49 UTC, closed without merging