Suggested spec change to resource locks (`lock`) interface for Terraform
Azure/Azure-Verified-Modules pull request #489
Opened 2024-01-04 12:19 UTC by MariusStorhaug

# Overview/Summary

## This PR fixes/adds/changes/removes

- Updates the suggestion for the terraform interface `lock`
- Fixes: #423

### Breaking Changes

N/A

## As part of this Pull Request I have

- [x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Verified-Modules/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Verified-Modules/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Verified-Modules/)
- [x] Ensured PR tests are passing
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-01-04 12:24 UTC, MariusStorhaug commented
@matt-FFFFFF: Opened a new PR with a working solution that should be closer to you suggestion while removing the "None" option.

2024-01-04 13:07 UTC, matt-FFFFFF commented
Hi thanks for the PR

I don't like the mixed use of a default and optional.

I prefer this:

```terraform
    type = object({
      name = optional(string, null)
      kind = optional(string, null)
    })
   default  = {}
   nullable = false
```

But with this validation:

```terraform
    validation {
      condition     = var.lock.kind == null || try(contains(["CanNotDelete", "ReadOnly"], var.lock.kind), false)
      error_message = "The lock level must be one of: `null`, '\"CanNotDelete\"', or '\"ReadOnly\"'."
    }
```

Also note the use of escaped quotes to differentiate `null` and `"null"`

2024-01-04 13:24 UTC, MariusStorhaug commented
I was thinking more that the `optional` keyword and function on `kind` would be 'lying' and not really showing the true spec of the object that is needed. Also when reading the docs it would indicate that `kind` is optional, while it is required if specifying the "lock" variable.

2024-01-04 14:25 UTC, matt-FFFFFF commented
> I was thinking more that the `optional` keyword and function on `kind` would be 'lying' and not really showing the true spec of the object that is needed. Also when reading the docs it would indicate that `kind` is optional, while it is required if specifying the `lock` variable.

Disagree here. It's the same in the MI interface and is IMHO cleaner.

2024-01-04 14:28 UTC, matt-FFFFFF requested changes

2024-01-04 14:28 UTC, matt-FFFFFF commented on docs/static/includes/interfaces/int.locks.schema.tf
> +    kind = string
```suggestion
    kind = optional(string, null)
```

2024-01-04 14:28 UTC, matt-FFFFFF commented on docs/static/includes/interfaces/int.locks.schema.tf
> +  }
```suggestion
  default     = {}
```

2024-01-04 14:28 UTC, matt-FFFFFF commented on docs/static/includes/interfaces/int.locks.schema.tf
> +    condition     = var.lock.kind != null ? contains(["CanNotDelete", "ReadOnly"], var.lock.kind) : true
```suggestion
    condition     = var.lock.kind == null || try(contains(["CanNotDelete", "ReadOnly"], var.lock.kind), false)
```

2024-01-04 14:28 UTC, matt-FFFFFF commented on docs/static/includes/interfaces/int.locks.schema.tf
> +    error_message = "The lock level must be one of: `null`, `CanNotDelete` or `ReadOnly`."
```suggestion
    error_message = "The lock level must be one of: `null`, `\"CanNotDelete\"` or `\"ReadOnly\"`."
```

2024-01-04 14:28 UTC, matt-FFFFFF commented on docs/static/includes/interfaces/int.locks.schema.tf
> +- `kind` - (Required) The type of lock. Possible values are `null`, `CanNotDelete` or `ReadOnly`.
```suggestion
- `kind` - (Required) The type of lock. Possible values are `null`, `\"CanNotDelete\"` or `\"ReadOnly\"`.
```

2024-01-04 14:42 UTC, MariusStorhaug commented
Well in contrast to the IM interface, the lock interface needs the `kind` variable provided in order to deploy the lock. The `managed_identities` has two attributes which indeed are marked as optional as you can provide one or the other or both, but one of the two attributes are actually required for the module to configure the identity feature on the resource.

Will go ahead with your code suggestions if you still disagree with my suggestions above.

2024-01-04 18:41 UTC, matt-FFFFFF commented
@MariusStorhaug Both approaches are semantically the same. Syntactically I prefer my proposal as it provides consistency with other interfaces and still fulfils the idiom of not specifying something means you don't get it.

2024-01-04 19:14 UTC, MariusStorhaug commented
@matt-FFFFFF Understood, all suggestions added.

2024-01-04 22:38 UTC, matt-FFFFFF commented
Hold fire. I've been thinking further on this and will discuss in the issue

2024-01-17 07:27 UTC, matt-FFFFFF commented
@MariusStorhaug 

Apologies for the flip flopping here - I agree with your original suggestion but have simplified the validation rule slightly:

```terraform

Apologies for radio silence here and for the flip flopping.

I have tested this and am happy with the code:

variable "lock" {
  type = object({
    kind = string
    name = optional(string, null)
  })
  default = null
  validation {
    error_message = "Lock kind must be either `CanNotDelete` or `ReadOnly`"
    condition     = var.lock != null ? contains(["CanNotDelete", "ReadOnly"], var.lock.kind) : true
  }
}

resource "terraform_data" "test" {
  count = var.lock != null ? 1 : 0
  input = {
    kind = var.lock.kind
    name = coalesce(var.lock.name, "lock-${var.name}")
  }
}

```

2024-01-21 09:25 UTC, MariusStorhaug commented
Update back to the original suggestion with a nullable lock variable and mandatory `kind` property, but merged the condition to be that of the other [suggested change, which was later reverted based on comments](https://github.com/Azure/Azure-Verified-Modules/pull/489#discussion_r1441825335).

2024-01-21 09:33 UTC, matt-FFFFFF approved these changes

2024-01-21 09:34 UTC, matt-FFFFFF commented
Thank you @MariusStorhaug - sorry again for the confusion

2024-01-21 09:34 UTC, merged